apiVersion: v1
kind: Service
metadata:
  name: httpserver-service
  namespace: default
spec:
  ports:
  - nodePort: 30001
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: http-server
  type: NodePort
